name: Deploy wendy to dev

on: workflow_dispatch

jobs:
  build_and_deploy:
    name: Building and deploying app
    runs-on: ubuntu-latest
    steps:
      - name: Install node.js and yarn
        uses: actions/checkout@v3
        with:
          node-version: '17.8.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies using yarn
        run: yarn install
        working-directory: ./GithubActions

      - name: Build the application
        run: yarn build
        working-directory: ./GithubActions
