name: Deploy wendy to dev

on: workflow_dispatch

jobs:
  build_and_deploy:
    name: Building and deploying app
    runs-on: ubuntu-latest
    steps:
      - name: Install node.js and yarn
        uses: actions/setup-node@v2
        with:
          node-version: '17.8.0'
      - name: Install dependencies using yarn
        run: yarn install
      - name: Build the application
        run: yarn build
