name: NodeJS with Webpack

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: '18.0.0'

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 17.8.0
        uses: actions/setup-node@v3
        with:
          node-version: '17.8.0'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build
